### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by S6Regen** [stevengj/Sobol.jl#12]
Maybe this is kind of neat for sub-random number generation:
[https://en.wikipedia.org/wiki/Low-discrepancy_sequence#Additive_recurrence](url)
You can use the golden ratio and some other ones:
[https://en.wikipedia.org/wiki/Silver_ratio](url)
[https://en.wikipedia.org/wiki/Plastic_number](url)
Luckily the wikipedia entries have the values in hexadecimal for coding and to check if the final digit in 32 or 64 bit is odd, which is better than even.

**Comment by stevengj** [comment]
Thanks for the comment.  However, the Sobol.jl package is just for generating Sobol sequences; other kinds of LDS should probably go in another package.
