### ISSUE TITLE
Skipping an exact number of elements

### ISSUE THREAD

**Issue by greimel** [stevengj/Sobol.jl#22]
In my application, I draw parameters from a `SobolSeq` and do some expensive simulations with them. I distribute the calculations across machines, so each machine is supposed to use a certain range of Sobol numbers.

Lets say, I want Sobol numbers `n:(n+m)`. How do I get them other than 
```julia
[next!(s) for 1:n+m][n+1:end]
```

Is there any benefit in using the existing skip function? Does it do something clever, or does it also compute and throw away the unwanted ones? 

Is there interest in adding this function to the package?
```julia
function skip_exact(s, n)
  n_eff = 2 ^ floor(Int, log(n) / log(2))
  Δ = n - n_eff
  skip(s, n)
  for i in 1:Δ
    next!(s)
  end
  s
end

# want to get the nth element
n = 10

s1 = SobolSeq(1)
x1 = [next!(s1)[1] for i in 1:n][n]

s2 = SobolSeq(1)
skip_exact(s2, n-1)
x2 = next!(s2)[1]

@assert x1 == x2
```

**Comment by stevengj** [comment]
I'm fine with this; probably better to just add an `exact=true` keyword option to the existing `skip` function.
